name: cryptocurrency_flutter
description: A new Flutter project.

publish_to: 'none'

version: 1.3.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  google_fonts: ^3.0.1
  nb_utils: ^4.5.2

  #Firebase
  firebase_core: ^1.17.0
  firebase_analytics: ^9.1.8
  firebase_crashlytics: ^2.8.0
  google_mobile_ads: ^1.2.0
  onesignal_flutter: ^3.3.0
  firebase_auth: ^3.3.18
  firebase_storage: ^10.2.16
  cloud_firestore: ^3.1.16

  # AppAnimations and functionality
  animated_bottom_navigation_bar: ^0.3.3
  shimmer: ^2.0.0
  lottie: ^1.3.0
  cached_network_image: ^3.2.1
  number_slide_animation: ^0.2.1
  readmore: ^2.1.0
  flutter_neumorphic: ^3.2.0

  #Charts
  chart_sparkline: ^1.0.11
  syncfusion_flutter_charts: ^20.1.57

  # Storage
  sqflite: ^2.0.2+1

  #API calling
  http: ^0.13.4
  html: ^0.15.0
  flutter_html: ^2.2.1
  intl: ^0.17.0

  # System Info
  package_info_plus: ^1.4.2
  url_launcher: ^6.1.2
  share_plus: ^4.0.4
  wakelock: ^0.6.1+2

  # State Management Technique
  mobx: ^2.0.7+2
  flutter_mobx: ^2.0.6+1

  # AUTHENTICATION
  google_sign_in: ^5.3.2
  the_apple_sign_in: ^1.1.1
  flutter_secure_storage: ^5.0.2

  image_picker: ^0.8.5+3

  flutter_slidable: ^1.3.0

  flutter_localizations:
    sdk: flutter
  carousel_slider: ^4.1.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  # State Management Technique
  build_runner: ^2.1.11
  mobx_codegen: ^2.0.7
  # flutter packages pub run build_runner build --delete-conflicting-outputs
flutter:

  uses-material-design: true

  assets:
    - images/
    - lang/
    - assets/
    - images/chart_images/
    - images/app_images/
    - images/social_images/
